### ISSUE TITLE
Web export broken in 1.2.0

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz#1339]
Tried to export to a volume, using test directory, and ended up with empty directories inside test - data/data but nothing written out. The error output from the 1.2.0 binary on Linux was
```
Traceback (most recent call last):
  File "/home/marcus/Tomviz-1.2.0-Linux-64bit/lib/tomviz/site-packages/tomviz/web.py", line 84, in web_export
    export_volume(dest, **kwargs)
  File "/home/marcus/Tomviz-1.2.0-Linux-64bit/lib/tomviz/site-packages/tomviz/web.py", line 624, in export_volume
    = jsMapping[arrayTypesMapping[scalars.GetDataType()]]
IndexError: string index out of range
Failed to execute the script.
```
I can test more with latest release. Tried volume with external data in this case.

**Comment by cjh1** [comment]
This seems to be working on master and  with 1.21.

**Comment by cjh1** [comment]
Closing this as I think web export if now working.
