### ISSUE TITLE
Crash when clicking on child data set in pipeline browser

### ISSUE THREAD

**Issue by cquammen** [OpenChemistry/tomviz#1375]
With commit 8f49a605108b72849d7db4316f6a9f9b0954933e (post major refactoring), perform the following steps:

* Launch tomviz
* Open a dataset
* Apply **Segmentation -> Binary Threshold**. Accept default parameters.
* Click on the child dataset named **Thresholded Segmentation**. tomviz will crash

Stack trace:

```
#0  0x00000000005cbac0 in tomviz::Pipeline::isRunning (this=0x0)
    at /home/cory.quammen/src/tomviz/tomviz/Pipeline.cxx:202
#1  0x0000000000592adc in tomviz::DeleteDataReaction::updateEnableState (
    this=0x2e95de0)
    at /home/cory.quammen/src/tomviz/tomviz/DeleteDataReaction.cxx:37
#2  0x0000000000592e2d in tomviz::DeleteDataReaction::activeDataSourceChanged (
    this=0x2e95de0)
    at /home/cory.quammen/src/tomviz/tomviz/DeleteDataReaction.cxx:77
#3  0x000000000063fe2f in tomviz::DeleteDataReaction::qt_static_metacall (
    _o=0x2e95de0, _c=QMetaObject::InvokeMetaMethod, _id=0, _a=0x7fffffffca30)
    at tomviz/tomvizlib_autogen/EWIEGA46WW/moc_DeleteDataReaction.cpp:72
#4  0x00007fffeb8eb469 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /home/cory.quammen/install/Qt5.9.1/5.9.1/gcc_64/lib/libQt5Core.so.5
#5  0x000000000063dfc4 in tomviz::ActiveObjects::dataSourceChanged (
    this=0x987fa0 <tomviz::ActiveObjects::instance()::theInstance>, 
    _t1=0x6902b30)
    at tomviz/tomvizlib_autogen/EWIEGA46WW/moc_ActiveObjects.cpp:395
#6  0x000000000054eb87 in tomviz::ActiveObjects::setActiveDataSource (
    this=0x987fa0 <tomviz::ActiveObjects::instance()::theInstance>, 
    source=0x6902b30)
    at /home/cory.quammen/src/tomviz/tomviz/ActiveObjects.cxx:95
#7  0x00000000005da970 in tomviz::PipelineView::currentChanged (this=0xbb2d60, 
    current=...) at /home/cory.quammen/src/tomviz/tomviz/PipelineView.cxx:472
#8  0x00007ffff5ea71c1 in ?? ()
   from /home/cory.quammen/install/Qt5.9.1/5.9.1/gcc_64/lib/libQt5Widgets.so.5
#9  0x00007fffeb8eb469 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /home/cory.quammen/install/Qt5.9.1/5.9.1/gcc_64/lib/libQt5Core.so.5
#10 0x00007fffeb873dea in QItemSelectionModel::currentChanged(QModelIndex const&, QModelIndex const&) ()
   from /home/cory.quammen/install/Qt5.9.1/5.9.1/gcc_64/lib/libQt5Core.so.5
#11 0x00007fffeb873fbd in QItemSelectionModel::setCurrentIndex(QModelIndex const&, QFlags<QItemSelectionModel::SelectionFlag>) ()
```
It looks like `DeleteDataReaction` assumes every `DataSource` points to a `Pipeline` when managing Qt connections, but apparently child `DataSource`s do not have a `Pipeline`.

**Comment by cquammen** [comment]
Fixed by #1376.
