### ISSUE TITLE
Restoring shift volume from state file fails

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz#1496]
I end up with a pipeline that looks like this:
![image](https://user-images.githubusercontent.com/42214/39005765-0b8b9086-43cf-11e8-977c-ec7934292759.png)
The error:
```
Traceback (most recent call last):
  File "Shift Volume", line 15, in transform_scalars
  File "/usr/lib/python3.6/site-packages/numpy/core/numeric.py", line 1393, in roll
    result[res_index] = a[arr_index]
TypeError: slice indices must be integers or None or have an __index__ method
Failed to execute the script.
```
Hitting apply repeats the error, and changing a shift and hitting apply causes a segfault.

**Comment by cryos** [comment]
It is basically an issue with round tripping using QJsonObject's to/from variant map. The serialize gets a bunch of integer types, but when reloading we end up with double precision types:
```
VariantMap: QMap(("pad_mode_index", QVariant(int, 0))("pad_size_after", QVariant(QVariantList, (QVariant(int, 3), QVariant(int, 5), QVariant(int, 7))))("pad_size_before", QVariant(QVariantList, (QVariant(int, 1), QVariant(int, 2), QVariant(int, 2)))))
VariantMap: QMap(("pad_mode_index", QVariant(double, 0))("pad_size_after", QVariant(QVariantList, (QVariant(double, 3), QVariant(double, 5), QVariant(double, 7))))("pad_size_before", QVariant(QVariantList, (QVariant(double, 1), QVariant(double, 2), QVariant(double, 2)))))
```
