### ISSUE TITLE
Crashes when deleting from pipeline

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1697]
Stability of tomviz reduced by deleting objects from pipeline.

(1) Load default datasets
(2) Delete everything from pipeline
(3) Run "generate random particles" change values to 256

Crashes.

Everything is OK if repeated without loading default datasets and deleting.

**Comment by psavery** [comment]
I was able to replicate this on Ubuntu 18.04, and I did a backtrace with gdb. Looks like it may be related to the 2D transfer functions? @mathturtle 

```
Thread 1 "tomviz" received signal SIGSEGV, Segmentation fault.
0x00007fffeec6b539 in vtkAOSDataArrayTemplate<float>::SetTuple (this=
    0x55555c324260, tupleIdx=<optimized out>, tuple=0x7fffffffd040)
    at ../VTK/Common/Core/vtkAOSDataArrayTemplate.txx:132
132	    data[i] = static_cast<ValueType>(tuple[i]);
(gdb) where
#0  0x00007fffeec6b539 in vtkAOSDataArrayTemplate<float>::SetTuple(long long, double const*) (this=0x55555c324260, tupleIdx=<optimized out>, tuple=0x7fffffffd040) at ../VTK/Common/Core/vtkAOSDataArrayTemplate.txx:132
#1  0x00005555556d4b9d in vtkTransferFunctionBoxItem::rasterTransferFunction2DBox(vtkImageData*, vtkRectd const&, vtkImageData*, vtkColorTransferFunction*, vtkPiecewiseFunction*) (histogram2D=<optimized out>, box=..., transferFunction=transferFunction@entry=0x55555d57b350, colorFunc=colorFunc@entry=
    0x55555cf0d580, opacFunc=opacFunc@entry=0x55555c056ab0)
    at ../tomviz/vtkTransferFunctionBoxItem.cxx:628
#2  0x00005555556d2ae1 in vtkChartTransfer2DEditor::GenerateTransfer2D() (this=
    0x555555e1d300) at ../tomviz/vtkChartTransfer2DEditor.cxx:129
#3  0x0000555555678b19 in tomviz::Histogram2DWidget::updateTransfer2D() (this=<optimized out>) at ../tomviz/Histogram2DWidget.cxx:141
#4  0x0000555555645686 in tomviz::CentralWidget::setColorMapDataSource(tomviz::DataSource*) (this=0x555555cb4ab0, source=<optimized out>)
    at ../tomviz/CentralWidget.cxx:270
#5  0x0000555555645a21 in tomviz::CentralWidget::histogram2DReady(vtkSmartPointer<vtkImageData>, vtkSmartPointer<vtkImageData>) (this=0x555555cb4ab0, input=..., output=...) at ../tomviz/CentralWidget.cxx:335
#6  0x0000555555646a09 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0, 1>, QtPrivate::List<vtkSmartPointer<vtkImageData>, vtkSmartPointer<vtkImageData> >, void, void (tomviz::CentralWidget::*)(vtkSmartPointer<vtkImageData>, vtkSmartPointer<vtkImageData>)>::call(void (tomviz::CentralWidget::*)(vtkSmartPointer<vtkIma---Type <return> to continue, or q <return> to quit---
geData>, vtkSmartPointer<vtkImageData>), tomviz::CentralWidget*, void**) (arg=0x7fffffffd3a0, o=<optimized out>, f=<optimized out>)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:136
#7  0x0000555555646a09 in QtPrivate::FunctionPointer<void (tomviz::CentralWidget::*)(vtkSmartPointer<vtkImageData>, vtkSmartPointer<vtkImageData>)>::call<QtPrivate::List<vtkSmartPointer<vtkImageData>, vtkSmartPointer<vtkImageData> >, void>(void (tomviz::CentralWidget::*)(vtkSmartPointer<vtkImageData>, vtkSmartPointer<vtkImageData>), tomviz::CentralWidget*, void**) (arg=0x7fffffffd3a0, o=<optimized out>, f=<optimized out>)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:169
#8  0x0000555555646a09 in QtPrivate::QSlotObject<void (tomviz::CentralWidget::*)(vtkSmartPointer<vtkImageData>, vtkSmartPointer<vtkImageData>), QtPrivate::List<vtkSmartPointer<vtkImageData>, vtkSmartPointer<vtkImageData> >, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=<optimized out>, this_=<optimized out>, r=<optimized out>, a=0x7fffffffd3a0, ret=<optimized out>)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h:120
#9  0x00007fffed8d56cf in QMetaObject::activate(QObject*, int, int, void**) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x0000555555743ffa in tomviz::HistogramManager::histogram2DReady(vtkSmartPointer<vtkImageData>, vtkSmartPointer<vtkImageData>) (this=this@entry=0x555555a4f200 <tomviz::HistogramManager::instance()::theInstance>, _t1=..., _t2=...)
    at tomviz/tomvizlib_autogen/EWIEGA46WW/moc_HistogramManager.cpp:164
#11 0x0000555555669406 in tomviz::HistogramManager::histogram2DReadyInternal(vtk---Type <return> to continue, or q <return> to quit---
SmartPointer<vtkImageData>, vtkSmartPointer<vtkImageData>) (this=this@entry=0x555555a4f200 <tomviz::HistogramManager::instance()::theInstance>, image=..., histogram=...) at ../tomviz/HistogramManager.cxx:328
#12 0x0000555555746513 in tomviz::HistogramManager::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x555555a4f200 <tomviz::HistogramManager::instance()::theInstance>, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>) at tomviz/tomvizlib_autogen/EWIEGA46WW/moc_HistogramManager.cpp:95
#13 0x00007fffed8d6122 in QObject::event(QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff5f9682c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff5f9e0f4 in QApplication::notify(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007fffed8a69a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007fffed8a911d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007fffed9002c3 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007fffe0891287 in g_main_context_dispatch ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007fffe08914c0 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007fffe089154c in g_main_context_iteration ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#22 0x00007fffed8ff8ef in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007fffed8a49ea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007fffed8ada84 in QCoreApplication::exec() ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00005555556236a7 in main(int, char**) (argc=<optimized out>, argv=0x7fffffffdd18) at ../tomviz/main.cxx:67
```

**Comment by mathturtle** [comment]
I can reproduce here too and I agree something to do with 2D transfer function is the cause.  I'm looking into it now.
