### ISSUE TITLE
Python 3.8 breaks the io search code

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz#2077]
When building my development environment most things work fine, but something has changed in Python 3.8 that breaks the io search code. This is consistent across a number of machines, I am not all that familiar with the code.
```
$ ./bin/tomviz 
Traceback (most recent call last):
  File "/home/marcus/build/tomvizsuper/tomviz/lib/site-packages/tomviz/io/_internal.py", line 19, in list_python_readers
    for _, c in inspect.getmembers(m, inspect.isclass):
  File "/usr/lib/python3.8/inspect.py", line 350, in getmembers
    value = getattr(object, key)
  File "/usr/lib/python3.8/site-packages/numpy/__init__.py", line 216, in __getattr__
    from .testing import Tester
ImportError: attempted relative import with no known parent package
Traceback (most recent call last):
  File "/home/marcus/build/tomvizsuper/tomviz/lib/site-packages/tomviz/io/_internal.py", line 44, in list_python_writers
    for _, c in inspect.getmembers(m, inspect.isclass):
  File "/usr/lib/python3.8/inspect.py", line 350, in getmembers
    value = getattr(object, key)
  File "/usr/lib/python3.8/site-packages/numpy/__init__.py", line 216, in __getattr__
    from .testing import Tester
ImportError: attempted relative import with no known parent package
"Error calling list_python_readers."
"Error calling list_python_writers."
```

**Comment by cryos** [comment]
This was resolved by the above PR.
