### ISSUE TITLE
Crashes when running "Sample Data > Generate Random Particles"

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#618]
Click "Sample Data > Generate Random Particles"
Then click OK.
Crashes

**Comment by mathturtle** [comment]
My first thought was a packaging issue, so I took a look.  But I can reproduce this in an environment where I know the dependencies are found.  Here is the relevant part of the stack trace:

```
#0  threadstate_getframe.lto_priv.1643 (self=0x0) at ../Python/pystate.c:153
#1  0x00007fffef9e5d79 in PyEval_GetGlobals () at ../Python/ceval.c:4135
#2  0x00007fffef953e72 in PyImport_Import (module_name=module_name@entry='tomviz.utils') at ../Python/import.c:2877
#3  0x00007fffef9540fa in PyImport_ImportModule (name=<optimized out>) at ../Python/import.c:2151
#4  0x000000000054af5b in (anonymous namespace)::PythonGeneratedDataSource::setScript (this=0x7fffffffccd0, script=...)
    at /home/shawn/dev/tomviz/src/tomviz/PythonGeneratedDatasetReaction.cxx:76
#5  0x000000000054d843 in tomviz::PythonGeneratedDatasetReaction::addDataset (this=0x210b480)
    at /home/shawn/dev/tomviz/src/tomviz/PythonGeneratedDatasetReaction.cxx:387
#6  0x000000000059e8e0 in tomviz::PythonGeneratedDatasetReaction::onTriggered (this=0x210b480)
    at tomviz/../../src/tomviz/PythonGeneratedDatasetReaction.h:46
#7  0x00007ffff78d5e26 in pqReaction::qt_static_metacall (_o=0x210b480, _c=QMetaObject::InvokeMetaMethod, _id=0, _a=0x7fffffffced0)
    at Qt/ApplicationComponents/moc_pqReaction.cpp:76
#8  0x00007ffff506d669 in QMetaObject::activate(QObject*, int, int, void**) () from /home/shawn/tools/qt5.7/lib/libQt5Core.so.5
#9  0x00007ffff5a44f32 in QAction::triggered(bool) () from /home/shawn/tools/qt5.7/lib/libQt5Widgets.so.5
#10 0x00007ffff5a478a0 in QAction::activate(QAction::ActionEvent) () from /home/shawn/tools/qt5.7/lib/libQt5Widgets.so.5
#11 0x00007ffff5bb37fa in ?? () from /home/shawn/tools/qt5.7/lib/libQt5Widgets.so.5
#12 0x00007ffff5bb9976 in ?? () from /home/shawn/tools/qt5.7/lib/libQt5Widgets.so.5
#13 0x00007ffff5bbda00 in QMenu::mouseReleaseEvent(QMouseEvent*) () from /home/shawn/tools/qt5.7/lib/libQt5Widgets.so.5
#14 0x00007ffff5a923a8 in QWidget::event(QEvent*) () from /home/shawn/tools/qt5.7/lib/libQt5Widgets.so.5
#15 0x00007ffff5bbe49b in QMenu::event(QEvent*) () from /home/shawn/tools/qt5.7/lib/libQt5Widgets.so.5
#16 0x00007ffff5a4b8ac in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /home/shawn/tools/qt5.7/lib/libQt5Widgets.so.5

```

@cjh1 It looks like something with python is failing.  Could this have to do with your python in the background thread branch?

**Comment by cjh1** [comment]
Yes, very likely, I was not aware of PythonGeneratedDatasetReaction, all the Python C API calls will need to be modified to work correctly with the GIL.

**Comment by cryos** [comment]
This is great, I wanted to have time to shake out all these corner cases before we make another release. Thanks for reporting these issues, and helping us track everything down!
